"""add language column to document

Revision ID: 23d8b1b413b5
Revises: 268e54b2f5bd
Create Date: 2021-01-03 16:36:07.001098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23d8b1b413b5"
down_revision = "268e54b2f5bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("language", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "language")
    # ### end Alembic commands ###
