"""add tsvector support

Revision ID: 268e54b2f5bd
Revises: 97567d02cdfd
Create Date: 2020-12-20 13:57:49.910558

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "268e54b2f5bd"
down_revision = "97567d02cdfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("fulltext", sa.String(), nullable=True))
    op.add_column(
        "document", sa.Column("fulltext_regconfig", sa.String(), nullable=True)
    )
    op.add_column(
        "document",
        sa.Column(
            "fulltext_search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
    )
    op.create_index(
        "Document_fulltext_search_vector_idx",
        "document",
        ["fulltext_search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("Document_fulltext_search_vector_idx", table_name="document")
    op.drop_column("document", "fulltext_search_vector")
    op.drop_column("document", "fulltext_regconfig")
    op.drop_column("document", "fulltext")
    # ### end Alembic commands ###
