"""make filename optional

Revision ID: 4cbbadd88af6
Revises: 3712b66b0ca3
Create Date: 2020-11-14 16:10:34.613557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4cbbadd88af6"
down_revision = "3712b66b0ca3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "filename", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "filename", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
