"""add word

Revision ID: 97567d02cdfd
Revises: 53d5b9085aa3
Create Date: 2020-11-23 09:28:00.356465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97567d02cdfd"
down_revision = "53d5b9085aa3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.Interval(), nullable=True),
        sa.Column("end_time", sa.Interval(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("fk_document", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_document"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_word_id"), "word", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_word_id"), table_name="word")
    op.drop_table("word")
    # ### end Alembic commands ###
