"""update wrt. initial orm

Revision ID: a93885e07b1c
Revises: d4867f3a4c0a
Create Date: 2020-11-08 19:14:37.425830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a93885e07b1c"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
